### PR TITLE
Add way filter and tests. Closes #1

### LINKED ISSUE #1: Implement "way" filter
This one should be very easy and is intended to get you comfortable in the project.

Have a look at the desired output that should be generated:
[Overpass_QL#Filters](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Filters).

The filter **node** is already implemented. The task now is to implement **way**.

Check out [Language_Guide](http://wiki.openstreetmap.org/wiki/Overpass_API/Language_Guide). Under every example you can see "Display result: OpenLayers map, JSON, XML.". Use those urls to fiddle around and try to write your own query by hand, including the new filter to be written. When satisfied, move on to coding.

Open OverpassFilterQuery.java, and look at how **node** is implemented. Now do the same for **way**, just under it.

Tailor the Javadoc for the new method.

Open OverpassFilterQueryTest.java, and create a test for the new method. 

Please leave issues of the same kind with **rel** and **area** filters for others, and move on to something more complex. You could even browse the [Overpass_QL](http://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL) documentation to look for features to be implemented.

### PR DESCRIPTION
**Pull request by JPMSoftwire**
Add the 'Way' filter.

I've only added an additional 'Example' test which is just a slight modification on the existing test - I couldn't see any other tests for the node filter, and am just getting to grips with the Overpass QL, so wanted to open this early to make sure I'm on the right path.

### CODE REVIEW

**Comment by zsoltk** [comment]
Right! Filter tests should be done in OverpassFilterQueryTest, which is missing - my bad! Don't worry about it now, I'll handle that. Apart from two minor formatting issues, your code is ok! I'll comment on those, and I'll merge when you fix those.

Thanks for the commit!

**Comment by JPMSoftwire** [comment]
Thanks for the feedback - should be fixed now.

**Comment by JPMSoftwire** [comment]
And now should actually be done!

**Comment by zsoltk** [comment]
Apologies, my second comment on indentation was a mistake on my part. I just noticed that my IDE flattened testExample1() and it had been commited that way, so of course you just copied what was already wrong. Fixing that now.

**Pull request merged**
